---
debian:9--gcc:
  image: docker.io/duneci/dune:git
  script: duneci-standard-test
  tags: [duneci]

debian:9--clang:
  image: docker.io/duneci/dune:git
  script: duneci-standard-test
  variables: {DUNECI_OPTS: /duneci/opts.clang}
  tags: [duneci]
